### ISSUE TITLE
What is the `r: 0,` parameter?

### ISSUE THREAD

**Issue by roblav96** [FrederickGeek8/LYQL#1]
@FrederickGeek8 Hey man! Awesome work with this project! Bravo 👏 

I'm wondering if you know what the `r=0` is used for in the [streamer query parameters](https://github.com/FrederickGeek8/LYQL/blob/af5c104cbc3ecd0c5bc1e5f7f057baa34ac13428/main.js#L62) `join(",") + "&>>>>>>>>r=0<<<<<<<<&callback=parent` Just curious is all =]

Also the `ts=1427741124050`, `mu=1`, `dp=1` if you don't mind 🌮

**Comment by FrederickGeek8** [comment]
Ah yes! Those are completely unnecessary parameters. I have removed them in the latest commit. Thanks for pointing that out!

**Comment by roblav96** [comment]
Thanks mate =]
